services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: alumdash-db
    environment:
      POSTGRES_DB: alumdash
      POSTGRES_USER: alumdash_user
      POSTGRES_PASSWORD: secure_alumdash_2025
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U alumdash_user -d alumdash"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # FastAPI Backend
  web:
    build: 
      context: .
      platforms:
        - linux/amd64
        - linux/arm64
    container_name: alumdash-web
    environment:
      DATABASE_URL: postgresql+asyncpg://alumdash_user:secure_alumdash_2025@db:5432/alumdash
      ENV: development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # Redis for caching and background tasks (optional)
  redis:
    image: redis:7-alpine
    container_name: alumdash-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
